# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 8083
  servlet:
    context-path: /proveedor
    session:
      cookie:
        name: UISESSION