# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 8082
  servlet:
    context-path: /cotizaciones
    session:
      cookie:
        name: UISESSION

# +-----------------------------------------------------
# |         SPRING CONFIG
# +-----------------------------------------------------
spring:
  security:
    oauth2:
      client:
        clientId: proveedores_app
        clientSecret: 8de6d4c46d616eb4c358ba6f63bb54dc
      resource:
        token-info-uri: http://security-service:8081/oauth/check_token
  thymeleaf:
    cache: false
  main:
    banner-mode: console
  application:
    name: cotizaciones
  datasource:
    url: jdbc:mysql://db_cotizaciones:3306/cotizacionesdb?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cotizaciones
    password: cotizaciones2020++
    platform: mysql
    initialization-mode: always
    #data: classpath:databases/mysql/mysql-data-v0.1.sql
    hikari:
      initialization-fail-timeout: 0
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      pool-name: cotizacionesPoolConetion
      connection-timeout: 60000
      maximum-pool-size: 5
    jmx:
      default-domain: startertest

# +-----------------------------------------------------
# |         SPRING LOGGIN CONFIG
# +-----------------------------------------------------
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss a} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"