# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 8080
  servlet:
    context-path: /middleware
    session:
      cookie:
        name: UISESSION