# +-----------------------------------------------------
# |         SERVER CONFIG
# +-----------------------------------------------------
server:
  port: 8081
  servlet:
    context-path: /security
    session:
      cookie:
        name: UISESSION

# +-----------------------------------------------------
# |         SPRING CONFIG
# +-----------------------------------------------------
spring:
  main:
    banner-mode: console
  application:
    name: security
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none # (create|none|update|create-drop|validate)
    show-sql: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistic: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://db_cotizaciones:3306/cotizacionesdb?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    url: jdbc:mysql://localhost:6603/cotizacionesdb?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: cotizaciones
    password: cotizaciones2020++
    platform: mysql
    initialization-mode: always
    hikari:
      initialization-fail-timeout: 0
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      pool-name: customerPoolConetion
      connection-timeout: 60000
      maximum-pool-size: 5
  jmx:
    default-domain: startertest

# +-----------------------------------------------------
# |         SPRING LOGGIN CONFIG
# +-----------------------------------------------------
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss a} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"