# -------------------------------------------------------------------
# - DOCKER COMPOSE FILE
# - AUTOR: Equipo 5
# - FECHA: 20-Abril-2020
# - DESCRIPCION: Docker compose file que permite la
# -              creacion de 2 contendores uno para la aplicacion
# -              y otro para la base de datos de proveedores
# -------------------------------------------------------------------

version: '3.7'
services:
  db_proveedores:
    container_name: db_proveedores
    image: mysql
    hostname: db_proveedores
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'proveedoresdb'
      MYSQL_USER: 'proveedores'
      MYSQL_PASSWORD: 'proveedores2020++'
    ports:
      - '6603:3306'
    volumes:
      - ./src/main/resources/databases/mysql/mysql-schema-v0.1.sql:/docker-entrypoint-initdb.d/mysql-schema-v0.1.sql
      - ./src/main/resources/databases/mysql/mysql-data-v0.1.sql:/docker-entrypoint-initdb.d/mysql-sdata-v0.1.sql
      - data_proveedores:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  proveedores:
    image: proveedores-service:latest
    container_name: proveedores-service
    hostname: proveedores-service
    restart: always
    ports:
      - 8060:8060
    networks:
      - backend
    depends_on:
      - db_proveedores
    environment:
      - SERVICE_PORTS=8060
      - DATABASE_HOST=db_proveedores
      - DATABASE_USER=proveedores
      - DATABASE_PASSWORD=proveedores2020++
      - DATABASE_NAME=proveedoresdb
      - DATABASE_PORT=6603
volumes:
  data_proveedores:
networks:
  backend:
    external: true
